build: change start port

diff --git a/.github/workflows/staging-pipline.yml b/.github/workflows/staging-pipline.yml
--- a/.github/workflows/staging-pipline.yml
+++ b/.github/workflows/staging-pipline.yml
@@ -16,22 +16,22 @@ jobs:
         with: 
           path: ./staging
 
-      # Set Environment Variables
-      - name: Set Environment Variables
-        run: |
-          echo "Staging branch detected"
-          chmod +x ./scripts/create_staging_env.sh
-          if [ ! -f ./scripts/create_staging_env.sh ]; then
-            echo "Script not found!"; exit 1;
-          fi
-          bash ./scripts/create_staging_env.sh
-          echo "FRONTEND_DIR=frontend-v2-staging" >> $GITHUB_ENV
-
       # Verify Current Directory
       - name: Verify Current Directory
         run: |
           echo "Current Directory: $(pwd)"
           ls -la
+      
+      # Set Environment Variables
+      - name: Set Environment Variables
+        run: |
+          echo "Staging branch detected"
+          chmod +x ./staging/scripts/create_staging_env.sh
+          if [ ! -f ./staging/scripts/create_staging_env.sh ]; then
+            echo "Script not found!"; exit 1;
+          fi
+          bash ./staging/scripts/create_staging_env.sh
+          echo "FRONTEND_DIR=frontend-v2-staging" >> $GITHUB_ENV
 
       # Verify Git Status
       - name: Verify Git Status
