ci: update dev pipline

diff --git a/.github/workflows/test-deployment.yml b/.github/workflows/test-deployment.yml
--- a/.github/workflows/test-deployment.yml
+++ b/.github/workflows/test-deployment.yml
@@ -10,28 +10,32 @@ jobs:
     runs-on: self-hosted
 
     steps:
+      # Checkout the code from the repository
       - name: Checkout code
         uses: actions/checkout@v3
 
-      # Set environment variables based on the branch (Main or Staging)
+      # Set environment variables
       - name: Set Environment Variables
         run: |
-            echo "Main branch detected"
-            chmod +x ./scripts/create_dev_env.sh
-            bash ./scripts/create_dev_env.sh
-            export FRONTEND_DIR=frontend-v2
-            export PORT=5600
+          echo "Main branch detected"
+          chmod +x ./scripts/create_dev_env.sh
+          if [ ! -f ./scripts/create_dev_env.sh ]; then
+            echo "create_dev_env.sh script not found! Exiting."; exit 1;
+          fi
+          bash ./scripts/create_dev_env.sh
+          echo "FRONTEND_DIR=frontend-v2" >> $GITHUB_ENV
+          echo "PORT=5600" >> $GITHUB_ENV
 
-      # Verify Current Directory
+      # Verify the current directory
       - name: Verify Current Directory
         run: |
           echo "Current Directory: $(pwd)"
           ls -la
           if [ ! -d ".git" ]; then
-            echo "No .git directory found. This is unexpected."
+            echo "No .git directory found. This is unexpected. Exiting."; exit 1;
           fi
 
-      # Verify Git Status
+      # Verify Git status
       - name: Verify Git Status
         run: |
           git status
@@ -39,21 +43,25 @@ jobs:
       # Install dependencies and build the application
       - name: Install dependencies and build the application
         run: |
-          git pull origin main
-          npm install --force
+          npm ci
           npm run build
 
-      - name: Create the jobs names
+      # Create job-related environment variables
+      - name: Create the job names
         run: |
-            echo "Main branch detected"
-            export JOB_NAME="gms-frontend"
-            export SCRIPT_NAME="development"
+          echo "Main branch detected"
+          echo "JOB_NAME=gms-dev" >> $GITHUB_ENV
+          echo "SCRIPT_NAME=development" >> $GITHUB_ENV
           echo "JOB_NAME=$JOB_NAME"
           echo "SCRIPT_NAME=$SCRIPT_NAME"
+
+      # Ensure pm2 is installed globally
+      - name: Install pm2 globally
+        run: |
+          npm install -g pm2
 
       # Start the application using pm2
       - name: Start the application using pm2
         run: |
-            echo "Main branch detected"
-          pm2 restart gms-frontend
+          pm2 restart gms-dev || pm2 start npm --name "gms-dev" -- start
           pm2 save
